### ISSUE TITLE
[Bug] Bosses get moved to RED team during BvB after some rounds

### ISSUE THREAD

**Issue by UberMedicFully** [Batfoxkid/Freak-Fortress-2-Rewrite#104]
## Description
(BvB) So, this bug tends to remove one boss to another after each round from the blue team and moves them to red, it will continue this until there is no one anymore in blue.

## Reproduce
1. Turn on BvB, 12 bosses each team.
2. Play a few or several rounds of BvB, unsure when it exactly starts happening
3. See error

## Environment
 - Linux
 - SourceMod Version/Build 6936
 - Freak Fortress Version/Build 1.1.125

## Other Information
No one will be able to join any team as soon there is no one in blue anymore.

**Comment by Batfoxkid** [comment]
Are you able to replicate this issue with just default subplugins?

**Comment by UberMedicFully** [comment]
Haven't tried that yet unfortunately, sorry for the slow respond.
