### ISSUE TITLE
[Request] ff2r_menu_abilities is missing global ability cooldown

### ISSUE THREAD

**Issue by naydef** [Batfoxkid/Freak-Fortress-2-Rewrite#110]
## Description
Just like the title says. Old ff2bat_menu_abilities offers `cooldownX` which applies cooldown to all 'spells' in the menu.
The lack of this feature prevents some of our bosses from being converted to new ff2r_menu_abilities.
I guess I can add the feature after some more source code investigation.

**Comment by naydef** [comment]
Nvm, there's already a report made for this: https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/issues/59
Closing.

**Comment by Frixux** [comment]
pls made this arg 👍
