### ISSUE TITLE
[Bug] ff2r_menu_abilities: flags arg seems not working

### ISSUE THREAD

**Issue by Frixux** [Batfoxkid/Freak-Fortress-2-Rewrite#114]
## Description
Flags arg seems not working, idk why but in naydef edit where added global cooldown, flags stopped working

## Reproduce
1. Use whatever flag you want, (i use 0x0008) (if you're in duo)
2. When partner died your flag, does not exclude a particular capability from the menu
3. see a error

**Comment by naydef** [comment]
This seems to be true, flag 0x10 also seems to be ded (when I expect it to disable the spell until last life).
I don't think the last commit is the cause of this issue, but I'll investigate.

**Comment by Frixux** [comment]
I mean, sorry I think it may not have been the fault of the last edit, just batfox may have forgotten to fix this bug.
