### ISSUE TITLE
[Bug] ff2r_menu_abilities: When your partner died, or player dies you can see the menu. 

### ISSUE THREAD

**Issue by Frixux** [Batfoxkid/Freak-Fortress-2-Rewrite#115]
## Description
when you are dead or in spectator, switch the view to the player who has the menu, you can see the menu 

## Reproduce
1. die or be in spectators 
2. switch to the player that have menu 
3. see a error

**Comment by Batfoxkid** [comment]
This is a normal effect when spectating a boss that's on your current team or if your in spectator.

**Comment by Frixux** [comment]
but if red dies too, a player can see this menu. can someone fix this?
