### ISSUE TITLE
[QUESTION] About adding CWX weapons.

### ISSUE THREAD

**Issue by TheGreatWeegee** [Batfoxkid/Freak-Fortress-2-Rewrite#12]
How exactly does adding CWX weapons work, and how do you define in config damage limit for "On Kill: do X" attributes?

Do you need to write every weapon manually in your weapon config instead of CWX's default system, or you can just add those weapon's names to your weapon config and freely add new attributes?
How do you write "On Kill: do X" damage stuff - is it sort of a specific attribute or it is a global ConVar?

**Comment by Batfoxkid** [comment]
CWX support simply allows changing stats of those weapons while the gamemode is active. This is mainly to support custom weapon servers that normally run CWX outside the gamemode and can change stats if needed for FF2.

On Kill effects simply means they work when hitting a boss, eg. "On Kill: Gain 25 health" would restore 25 health on hitting a boss.

**Comment by TheGreatWeegee** [comment]
Got it, thank you for your explanation!
