### ISSUE TITLE
[Bug] Weapon can't have attribute and custom section at once unlike our intention

### ISSUE THREAD

**Issue by M60TM** [Batfoxkid/Freak-Fortress-2-Rewrite#132]
## Description
If weapon have attribute and custom section at once, custom attribute section will ignored.

## Reproduce
This is example on wiki.
```
"CWX"	// Custom Weapons X
{
	"{e86f9513-1454-49dd-97b1-ce1faab2f89e}"	// Weapon ID
	{
		"strip"		"false"	// If to strip all attributes
		
		"attributes"	// Named attributes
		{
			"airblast cost scale hidden"	"0.5"	// Overrides attribute
		}
		
		"custom"	// Custom attributes
		{
			"damage vs bosses"	"2.0"
			"mod airblast stale"	"0.2"
		}
	}
}
```
But custom section will be ignored in-game.

## Code that have problem
https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/blob/main/addons/sourcemod/scripting/freak_fortress_2/weapons.sp#L355
https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/blob/main/addons/sourcemod/scripting/freak_fortress_2/weapons.sp#L854
```
		case KeyValType_Section:
		{
			cfg = cfg.GetSection("attributes");

			StringMapSnapshot snap = cfg.Snapshot();
			int entries = snap.Length;

			PackVal attributeValue;

			for(int i = 0; i < entries; i++)
			{
				int length = snap.KeyBufferSize(i) + 1;
				char[] key = new char[length];

				snap.GetKey(i, key, length);
				
				cfg.GetArray(key, attributeValue, sizeof(attributeValue));

				if(attributeValue.tag == KeyValType_Value)
				{
					TF2Attrib_SetFromStringValue(entity, key, attributeValue.data);
				}
			}

			delete snap;
		}
	}
	
	cfg = cfg.GetSection("custom");
	if(cfg)
		Weapons_ApplyCustomAttributes(entity, cfg);
}
```
If `attribute`'s KeyValType is section, `cfg` will be assigned by attribute section. This is cause of problem.

**Comment by Zabaniya001** [comment]
Yeah, you're supposed to put the "custom" section inside "attributes".

**Comment by M60TM** [comment]
Huh, I didn't know that commit. I'll close this.
