### ISSUE TITLE
[Bug] Unknown bug that causes players to not join any team

### ISSUE THREAD

**Issue by DanishSoup** [Batfoxkid/Freak-Fortress-2-Rewrite#135]
## Description
A bug that doesn't allow any players to join any team other than spectator. Rarely when a new map starts in the beginning of the round starts, a bot that spawns to fill up another slot to make sure 1 player can play the game by themselves. The bot doesn't spawn and everyone is forced to move to spectator to get the ability to join into a team. No idea if its the bots problem or not.

## Media
If applicable, add screenshots, videos, logs, to help explain your problem.
https://youtu.be/EgaKuhzXHsI

## Environment
 - OS: [e.g. Windows]: Linux
 - SourceMod Version/Build: 
 - Freak Fortress Version/Build: 1.1.150

## Other Information
Could not be replicated on my private test server. Only happens on the public server that runs ff2:r

**Comment by kelvinthh** [comment]
This happens to my server as well. But it usually occurs only on the first map after the server starts. My server has tf_bot_quota set to 13. So I'm not sure if this is something related to bots as well.
