### ISSUE TITLE
[Bug]  I can't join the blue team in any way. The round doesn't start. What to do?

### ISSUE THREAD

**Issue by KarlHelsenberg** [Batfoxkid/Freak-Fortress-2-Rewrite#136]
## Media
If applicable, add screenshots, videos, logs, to help explain your problem.

## Environment
 - OS: [Linux]
 - SourceMod (1.11.0.6928) by AlliedModders LLC
 - Freak Fortress Rewrite 1.1.150

**Comment by M60TM** [comment]
Did you load ff2r by map-configs?
