### ISSUE TITLE
[Request] Boss speed management 

### ISSUE THREAD

**Issue by samuuuuuuuu** [Batfoxkid/Freak-Fortress-2-Rewrite#139]
## Description
Add an extra boss option named "speedcap" where you can define what the ACTUAL maximum speed of a boss has to be.
Currently, "maxspeed" doesn't set a maximum speed that the boss can go at, but rather is the starting speed of a boss.
The boss then speeds up during the round.

## Applications
Would be useful for static-speed bosses, or for bosses who have a high speed at first and slow down the more HP they lose.

## Other Information
If possible, add other options to define if a boss should change his speed by a % whenever aiming with a minigun, huntsman/sniper rifle, using the BFB or getting a speedboost/slowdown.

**Comment by Batfoxkid** [comment]
[Dynamic Defaults](https://forums.alliedmods.net/showthread.php?t=258090) already does a similar feature and better off being external
