### ISSUE TITLE
[ADDITION?] Throwing Sapper Implementation.

### ISSUE THREAD

**Issue by TheGreatWeegee** [Batfoxkid/Freak-Fortress-2-Rewrite#14]
I wanted to suggest a couple of things, but I decided to separate both things into different issues.
One of them - this one - can be added when the rewrite will be a bit more stable.

In short, wanted to suggest an optional support for throwable sapper - for example ability to remove rage and slow hale when he is in radius of a sapper. Rage drain rate and slowdown can be configurable through custom attributes.
[https://github.com/Chdata/TF2-Throwable-Sapper](url)

**Comment by Batfoxkid** [comment]
I won't be doing this as a main line weapon change, it can still be done through an external subplugin just not going to include as part of the defaults here.
