### ISSUE TITLE
[Bug] attribute 296 `sapper kills collect crits` doesn't work as we intended

### ISSUE THREAD

**Issue by M60TM** [Batfoxkid/Freak-Fortress-2-Rewrite#171]
## Description
As intended, the higher the value of attribute 296, the more critical should be given, but if the value is higher than 1, it will not work.

## Reproduce
1. Setting `sapper kills collect crits` to any higher value than 1 on diamondback.
2. Backstab boss and See.

## Reason
`bool SapperKillsCollectCrits( void ) const { int iMode = 0; CALL_ATTRIB_HOOK_INT( iMode, sapper_kills_collect_crits ); return (iMode == 1); };`

**Comment by M60TM** [comment]
As a result of decompiling server_srv.so, the function above no longer exists and is hard-coded within each function. I was thinking of using DHooks for this, but it became impossible.

**Comment by Batfoxkid** [comment]
Overriding the SapperKillsCollectCrits might be out of scope for FF2 specifically.
