### ISSUE TITLE
[Bug] Installed bosses do not appear in the menu and do not get selected for being played with either.

### ISSUE THREAD

**Issue by pootispenserhere4723** [Batfoxkid/Freak-Fortress-2-Rewrite#180]
## Description
I installed some custom bosses in my server but they don't appear on the ff2boss list or get selected for being played with.

## Media
If applicable, add screenshots, videos, logs, to help explain your problem.

## Environment
 - OS: Linux Mint 21.3
 - SourceMod Version/Build: 6954 (Linux Latest)
 - Freak Fortress Version/Build: 1.1.17

## Other Information
Unrelated, but Vagineer seems to lag the shit out of the running server.

**Comment by naydef** [comment]
Post any relevant error logs. Post your characters.cfg config? Maybe the problematic boss configs?

**Comment by pootispenserhere4723** [comment]
[bosses that dont work.zip](https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/files/14480883/bosses.that.dont.work.zip)
Here's two of the bosses i have installed (had to put them in a zip file because github doesnt let me post the cfg files alone)

**Comment by pootispenserhere4723** [comment]
That seemed to work, but when a bot (had to use tf_bots for testing) gets selected as custom boss the entire server has a seizure and lags a shit ton. Will try on another computer to see if such bots are the problem.

**Comment by pootispenserhere4723** [comment]
The bot lag problem seemed to be cause of me having the bot overhaul mod installed.
