### ISSUE TITLE
[Addition] Russian Translation

### ISSUE THREAD

**Issue by 1BLODY** [Batfoxkid/Freak-Fortress-2-Rewrite#184]
## Description
Adding a russian translation can make this gamemode more accessible to russian speaking users.

## Other Information
Special thanks to @TheGreatWeegee for helping me fix minor spelling mistakes and helping with translation.

## Download Link
[ff2_rewrite.phrases.txt](https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/files/14640866/ff2_rewrite.phrases.txt)

**Comment by Batfoxkid** [comment]
Your free to [fork and open a pull request](https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/fork) to add this change.
