### ISSUE TITLE
[Bug] Sentry gun gives assist kills for each hit

### ISSUE THREAD

**Issue by DanishSoup** [Batfoxkid/Freak-Fortress-2-Rewrite#189]
## Description
When using a sentry, everytime the sentry shoots it counts as an assist which can be used with the frontier justice to get revenge crits

## Reproduce
1. Place down sentry
2. Make it attack boss
3. See error

## Media
If applicable, add screenshots, videos, logs, to help explain your problem.
https://youtu.be/Fd_J99Lj1o0

## Environment
 - OS: [e.g. Windows] Linux Mint 21.3
 - SourceMod Version/Build: 1.12.0.7043
 - Freak Fortress Version/Build: 1.1.187

**Comment by Batfoxkid** [comment]
Was fixed in 1.1.188
