### ISSUE TITLE
[Bug] FF2 Music Pugin not working properly

### ISSUE THREAD

**Issue by SunnyasOmori** [Batfoxkid/Freak-Fortress-2-Rewrite#191]
## Description
The hale music doesn't end properly, continuing playing or overlaying over the new round hale music.

**Comment by DanishSoup** [comment]
Apparently this is only happening on the server we're running ff2 on and not my test server which boss music will end just fine on round end.

**Comment by naydef** [comment]
Are you using music replacement plugin? If yes, then depending on the situation these can be replaced with regular music declaration in the boss config.

**Comment by DanishSoup** [comment]
Doesn't appear we have anything like that. Just been using the regular rewrite plugin to handle the music

**Comment by Batfoxkid** [comment]
Need more info about how to replicate this problem
