### ISSUE TITLE
[Bug] The Beggar's Bazooka ammo bug

### ISSUE THREAD

**Issue by Fate977** [Batfoxkid/Freak-Fortress-2-Rewrite#194]
In theory, it should be able to launch 3 missiles at once, but it doesn't work
```
        "730"
	{
		"strip"		"false"
		"attributes"
		{
			"fire rate bonus HIDDEN"	"0.2"
			"reload time increased hidden"	"1.3"
			"clip size penalty"	"0.75"
			"projectile spread angle penalty"	"5.0"
			"fire rate bonus"	"0.1"
			"mini rockets"	"1.5"
			"auto fires full clip"	"1.0"
		}
	}
```
[VIDEO](https://www.youtube.com/watch?v=89tfFPv3wtM)

**Comment by Batfoxkid** [comment]
Your adding a reduction of clip size on top of existing clip size reduction that the Begger's Bazooka already has. You may be better off setting `"strip"` to 1 if you wish to override existing attributes it already has with your own.

**Comment by Fate977** [comment]
> Your adding a reduction of clip size on top of existing clip size reduction that the Begger's Bazooka already has. You may be better off setting `"strip"` to 1 if you wish to override existing attributes it already has with your own.

[video](https://youtu.be/S55FJxjEQ0g)
