### ISSUE TITLE
[Bug] Home teleport block can be circumvented with eureka_teleport 1.

### ISSUE THREAD

**Issue by minesettimi** [Batfoxkid/Freak-Fortress-2-Rewrite#20]
## Description
If a player uses eureka_teleport 1 in console when they have the eureka effect they can teleport to home.

## Reproduce
1. Download and compile Freak Fortress 2 Rewrite
2.  Play as engineer with eureka effect
3.  At any time put eureka_teleport 1 in console.

## Environment
 - OS: Linux

## Other Information
This will remove the stun effect and on certain maps make an almost-uncatchable engineer.

**Comment by Batfoxkid** [comment]
Fixed in https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/commit/2eb66f95973d69244e4fc0dfbe369f4bc2e2f752
