### ISSUE TITLE
[Bug] ff2r_default_abilities: rage_cloneattack: sometimes instead of minions respawn t-posing scouts and heavies

### ISSUE THREAD

**Issue by Frixux** [Batfoxkid/Freak-Fortress-2-Rewrite#211]
## Description
Check Title 

## Environment
 - OS: Linux
 - SourceMod: 1.11.0.6964
 - Freak Fortress: 1.1.192

**Comment by Batfoxkid** [comment]
Need more info about how to replicate this problem
