### ISSUE TITLE
[Bug] Boss rage crashes the server on occasion. 

### ISSUE THREAD

**Issue by minesettimi** [Batfoxkid/Freak-Fortress-2-Rewrite#22]
## Description
Whenever the boss rages theres a seemingly random chance that it crashes the server.

## Reproduce
1. Download and compile vanilla Freak Fortress Rewrite
2. Play as normal
3. At some point when a boss rages the server crashes.

## Environment
 - OS: Linux
 - SourceMod 1.11.0.6906, jit-x86 (build 1.11.0.6906)

## Media
https://crash.limetech.org/5i2rzrftqvpw
https://crash.limetech.org/pc3rwotg2vki
https://crash.limetech.org/dj4aoqdglyvk

**Comment by Batfoxkid** [comment]
This is indeed a gamedata issue for Linux. Does it appear to happen only with rage_stun from ff2r_default_abilities?

**Comment by minesettimi** [comment]
I only use the default subplugins and bosses which iirc all use rage_stun from ff2r_default_abilities although if it helps ive noticed that the crash is more likely to happen on bosses that give weapons such as brutal sniper and gentle spy.

**Comment by Batfoxkid** [comment]
Patched in the latest release, lag compensation was re-enabled.
