### ISSUE TITLE
At the change/start of the map, i can not enter the blue/red team

### ISSUE THREAD

**Issue by Frixux** [Batfoxkid/Freak-Fortress-2-Rewrite#37]
I don't know if you have the same thing, but please help, either it's my fault or something with the plugin, on changing the map every player can't enter to red or blue team, and  then i need to spawn a bot to enter normally, please help.
sorry for my bad english.

**Comment by Batfoxkid** [comment]
Any errors reported in the error log, located in `tf/addons/sourcemod/logs/error_X.log`?

**Comment by Frixux** [comment]
L 10/17/2022 - 22:20:22: SourceMod log file session started (file "/home/k27753_s20695/server_20695/tf/addons/sourcemod/logs/L20221017.log") (Version "1.11.0.6911")
L 10/17/2022 - 22:20:22: [TF2ITEMS] "GiveNamedItem" offset = 489
L 10/17/2022 - 22:20:22: [simple-chatprocessor.smx] [SCP] Recognized mod [Team Fortress 2].
L 10/17/2022 - 22:20:22: [simple-chatprocessor.smx] [SCP] Loading translation file [scp.tf.phrases].
L 10/17/2022 - 22:20:22: [funcommandsX.smx] Game detected as Team Fortress 2: Source (GAME_TF2)
L 10/17/2022 - 22:20:28: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sm_advertisements_interval") (value "1600")
L 10/17/2022 - 22:20:28: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "tf_forced_holiday") (value "2")
L 10/17/2022 - 22:20:28: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "caber_timer") (value "30")
L 10/17/2022 - 22:20:28: [mapchooser_extended.smx] Loaded map list for tf.

its all

**Comment by Frixux** [comment]
L 10/17/2022 - 22:20:22: [TF2ITEMS] "GiveNamedItem" offset = 489
L 10/17/2022 - 22:20:22: [simple-chatprocessor.smx] [SCP] Recognized mod [Team Fortress 2].
L 10/17/2022 - 22:20:22: [simple-chatprocessor.smx] [SCP] Loading translation file [scp.tf.phrases].
L 10/17/2022 - 22:20:22: [funcommandsX.smx] Game detected as Team Fortress 2: Source (GAME_TF2)
L 10/17/2022 - 22:20:28: [basecommands.smx] "Console<0>" changed cvar (cvar "sm_advertisements_interval") (value "1600")
L 10/17/2022 - 22:20:28: [basecommands.smx] "Console<0>" changed cvar (cvar "tf_forced_holiday") (value "2")
L 10/17/2022 - 22:20:28: [basecommands.smx] "Console<0>" changed cvar (cvar "caber_timer") (value "30")
L 10/17/2022 - 22:20:28: [mapchooser_extended.smx] Loaded map list for tf.

its all

**Comment by Frixux** [comment]
L 10/17/2022 - 22:20:22: Info (map "vsh_coldvine_b1") (file
L 10/17/2022 - 22:20:22: [SM] Exception reported: Failed to create native "NominateMap", name is probably already in use
L 10/17/2022 - 22:20:22: [SM] Blaming: nativevotes_mapchooser.smx
L 10/17/2022 - 22:20:22: [SM] Call stack trace:
L 10/17/2022 - 22:20:22: [SM]   [0] CreateNative
L 10/17/2022 - 22:20:22: [SM]   [1] Line 202, nativevotes_mapchooser.sp::AskPluginLoad2
L 10/17/2022 - 22:20:22: [SM] Failed to load plugin "nativevotes_mapchooser.smx": unexpected error 23 in AskPluginLoad callback.
its all

**Comment by Batfoxkid** [comment]
Make sure to resolve any conflicting plugins that could interfere with team swaps or anything similar.

**Comment by Frixux** [comment]
i didn't have any conflicting plugins.

**Comment by saxybois** [comment]
I have the same problem, gamemode only starts after creating a bot.
