### ISSUE TITLE
Weapon Attributes

### ISSUE THREAD

**Issue by Zabaniya001** [Batfoxkid/Freak-Fortress-2-Rewrite#4]
# Move from Attribute IDs to Named Attributes

I think it'd be beneficial to **move away from attribute IDs** and **replace them with named attributes**. 
It's easier to understand what attributes a weapon has and it's faster to change the value, rather than having a number that doesn't make any sense unless you have the attributes spreadsheet at hand.
It's way easier to understand hands down. That would / could also be applied to boss weapons.

It's a system that we use and here is an example:

![image](https://user-images.githubusercontent.com/73082112/167299115-316958b1-cfe5-46ad-9f57-8424781e9c2c.png)

This is what it could look like if FF2-Re used a similar system:

![image](https://user-images.githubusercontent.com/73082112/167299451-e5cfcb84-edc8-4839-8922-ea04824537e9.png)

***
### What about backwards compatibility?
We can easily keep the previous system by simply checking if it has a subsection. People wouldn't have to be forced to change every config if they're switching from FF2.

**Comment by Zabaniya001** [comment]
If this gets greenlit I can work on it.

**Comment by Batfoxkid** [comment]
I'm all fine with this idea 👍

**Comment by Zabaniya001** [comment]
Merged #7
