### ISSUE TITLE
[Bug] On Win as boss, boss just t-pose with, his minions too + On the first round, the music turns on before the round begins

### ISSUE THREAD

**Issue by Frixux** [Batfoxkid/Freak-Fortress-2-Rewrite#40]
## Description
after winning a round, as the boss on my server, boss loses his weapon and puts himself in the t position, minions do the same thing
second bug; On the first round, the music turns on before the round begins

## Reproduce
1.Select any bosses
2.Win Round.
second bug:
1.Play on first round as boss
2. Music will play before round begin.

## Media
https://www.youtube.com/watch?v=5_ZjIwurM8E&ab_channel=DemoSamedi
https://www.youtube.com/watch?v=Ul6DPuhBIX0&ab_channel=DemoSamedi 
https://www.youtube.com/watch?v=VrNrB927T8I&ab_channel=DemoSamedi

## Environment
 - OS: Linux
 - SourceMod Version/Build: 1.11.0.6917
 - Freak Fortress Version/Build: 1.1.91

**Comment by Batfoxkid** [comment]
Can't seem to replicate music playing before round start, do you mind sharing your boss config?

**Comment by Frixux** [comment]
Yeah Sure

"sound_bgm"
	{
		"freak_fortress_2/new_spookmaster/new_spookmaster_theme2.mp3"
		{
			"time"		"339.0"
			"name"		"Hang'em All"
			"artist"	"Carpenter Brut"
		}
                "freak_fortress_2/new_spookmaster/new_spookmaster_theme4.mp3"
		{
			"time"		"278.0"
			"name"		"Maniac"
			"artist"	"Carpenter Brut"
		}

**Comment by Batfoxkid** [comment]
I would like to see more of the config such as other sound arguments.

**Comment by Frixux** [comment]
"sound_begin"
	{
		"freak_fortress_2/new_spookmaster/new_spookmaster_intro2.mp3"	        ""
	}
	"sound_win"
	{
		"freak_fortress_2/new_spookmaster/new_spookmaster_win1.mp3"             ""
	}
	"sound_death"
	{
		"freak_fortress_2/new_spookmaster/original_spookmaster_death.mp3"       ""
	}
	"sound_kill"
	{
                "freak_fortress_2/new_spookmaster/kill1.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill2.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill3.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill4.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill5.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill6.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill7.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill8.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill9.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill10.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill11.mp3"	                        ""  
                "freak_fortress_2/new_spookmaster/kill12.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill13.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill14.mp3"	                        ""
                "freak_fortress_2/new_spookmaster/kill15.mp3"	                        ""
	}
        "sound_kspree"
	{
		"freak_fortress_2/new_spookmaster/new_spookmaster_kspree1.mp3"	        ""
                "freak_fortress_2/new_spookmaster/new_spookmaster_kspree2.mp3"	        ""
                "freak_fortress_2/new_spookmaster/original_spookmaster_kspree.mp3"      ""
	} 
        "catch_phrase"
	{
		"freak_fortress_2/new_spookmaster/original_spookmaster_kill.mp3"	""
	}
        "sound_ability"
	{
		"freak_fortress_2/new_spookmaster/new_spookmaster_kspree2.mp3"	        ""
		
		"freak_fortress_2/new_spookmaster/original_spookmaster_kill.mp3"	"1"
	}  
	"sound_stabbed"
	{
		"freak_fortress_2/new_spookmaster/new_spookmaster_backstab1.mp3"        ""
                "freak_fortress_2/new_spookmaster/new_spookmaster_backstab2.mp3"        ""
	}
        "sound_nextlife"
	{
		"1"		"freak_fortress_2/new_spookmaster/spookmaster_bgm_original2.mp3" 
		"1music"	"432.0"
		"1name"		"Inferno (Cinder's Theme)"
		"1artist"	"Mick Gordon"
	}
	"sound_bgm"
	{
		"freak_fortress_2/new_spookmaster/new_spookmaster_theme2.mp3"
		{
			"time"		"339.0"
			"name"		"Hang'em All"
			"artist"	"Carpenter Brut"
		}
                "freak_fortress_2/new_spookmaster/new_spookmaster_theme4.mp3"
		{
			"time"		"278.0"
			"name"		"Maniac"
			"artist"	"Carpenter Brut"
		}
	}
        "sound_precache"
	{
                "freak_fortress_2/new_spookmaster/spookmaster_bgm_original.mp3"       ""
		"freak_fortress_2/new_spookmaster/spookmaster_bgm_original2.mp3"      ""
                "freak_fortress_2/new_spookmaster/boner_ragemode.mp3"                 ""
                "freak_fortress_2/new_spookmaster/boner_ragemode2.mp3"                ""
	}

**Comment by Batfoxkid** [comment]
After some testing, it's found that nothing with base FF2R and it's subplugins can cause this issue.
A likely bad plugin using FF2_StartMusic early in the round might be at fault.
