### ISSUE TITLE
[Bug] damage_penalty/damage_bonus doesn't work on boss's weapons

### ISSUE THREAD

**Issue by TheGreatWeegee** [Batfoxkid/Freak-Fortress-2-Rewrite#43]
## Description
Neither damage_penalty nor damage_bonus attribute are working on the weapons (melee weapons at the very least) - they all deal by default 100 damage. From what I heard from other users, it also do affect the other damage modifiers on weapon, like **CARD: damage bonus** attribute, except the "dmg penalty vs players" and "dmg bonus vs buildings" attributes.

## Reproduce
1. Make a boss with any damage multiplier except the "dmg penalty vs players" and "dmg bonus vs buildings" attributes.
2. Launch server and pick this boss
3. Deal damage to players
4. Add "dmg penalty vs players" attribute to boss weapon instead of damage bonus/damage penalty
5. Reload charset and pick this boss again
6. Deal damage to players again

## Environment
- OS: Linux
- SourceMod Version 1.11.0.6914/Build 1.11.0.6914
- Freak Fortress Version 1.1./Build (timestamp): 10/14/2022 03:38:45

## Other Information
I've had this bug before on both my test server, and a server I've been setting up for my friend - I'm not sure if this was fixed in the newest versions, but decided to still report it.

**Comment by Batfoxkid** [comment]
Does this effect only take place when attempting to reload the charset? As well does this happen on newer versions?

**Comment by TheGreatWeegee** [comment]
No, it doesn't. It also happens when you just launch the server.
As of new versions, I haven't tested it, but I will look into it either today but a bit later or tomorrow.

**Comment by Batfoxkid** [comment]
Can't seem to replicate this bug, if anyone else experiences this issue let me know.
