### ISSUE TITLE
[Bug] FF2R Seems to cause MvM waves to not start after the map has changed from FF2 gamemode

### ISSUE THREAD

**Issue by StShAzzy** [Batfoxkid/Freak-Fortress-2-Rewrite#45]
## Reproduce
1. Play Freak Fortress 2 for atleast 1 round
2. Change to a MvM map
3. Watch the F4 Text not appearing and pressing F4 not doing anything

## Media
![image](https://user-images.githubusercontent.com/90798128/205529687-9766ee16-42af-48d9-a9e5-e68cc7454e79.png)
(image showing the F4 text not showing up, and the wave not started

## Environment
 - OS: Windows 10 Pro (18362.1500)
 - SM 1.11.6923
 - FF2R 1.1.98

## Other Information
I'm still investigating this issue, and getting the you (the owner of the plugin) to give this some attention may be useful into getting it fixed

**Comment by Batfoxkid** [comment]
I have heard that MvM is currently experiencing issues in the latest update. Other things I wonder is:
1. Is FF2 loaded during this time or what is the current maps.cfg config set for mvm related maps
2. Does this issue also happen without FF2 when switching from Arena to MvM

**Comment by StShAzzy** [comment]
> I have heard that MvM is currently experiencing issues in the latest update. Other things I wonder is:
> 
> 1. Is FF2 loaded during this time or what is the current maps.cfg config set for mvm related maps
> 2. Does this issue also happen without FF2 when switching from Arena to MvM

for 1st, no, the 2nd question i never tested that actually

**Comment by Batfoxkid** [comment]
And update on this issue?

**Comment by StShAzzy** [comment]
true... i completely forgot about this, so... i'll look into it today, but not now since it's 4 AM, and i gotta rest

**Comment by StShAzzy** [comment]
no, it doesn't happen when changing from Arena to MvM
