### ISSUE TITLE
[Bug] Bug to join and play in Boss side

### ISSUE THREAD

**Issue by Herneval** [Batfoxkid/Freak-Fortress-2-Rewrite#46]
## Description
There's a bug with BvB disabled that lets you enter to Boss (BLU side) and play with him. You will have minicrits (because it's 2 in the same time, haven't tested with other player, but Crit rules may apply), cannot heal you and the boss, etcetera.

## Reproduce
1. When round finish, reconnect to the server.
2. Skip game tips and choose a class.
3. You're now in blue team and you can play normally.

## Media

https://user-images.githubusercontent.com/45585078/205555330-057255e1-4e9c-4c4d-907c-48572091ad42.mp4

## Environment
 - OS: Linux
 - SourceMod 1.12.0.6942
 - Freak Fortress 1.1.95

**Comment by Batfoxkid** [comment]
Can't seem to replicate this issue, check if you have any special cvars changed or any plugins. If this still seems to be a problem for you, try `ff2_aggressive_noswap "1"` which will force teams regardless of other plugins.
