### ISSUE TITLE
[Bug] Server seems to crash during a round on a map change

### ISSUE THREAD

**Issue by UberMedicFully** [Batfoxkid/Freak-Fortress-2-Rewrite#48]
It seems like changing the map during a round causes a crash

assuming its a issue of the plugin itself, dont think this matters but i tested this on the latest ff2 rewrite on windows

**Comment by Frixux** [comment]
yeah i have the same problem.

**Comment by Batfoxkid** [comment]
Fixed in latest release https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/commit/913a07cfbba7b01e3d6cfd4602d270888a45078a

**Comment by Fate970730** [comment]
yeah i have the same problem.

**Comment by Batfoxkid** [comment]
> 2023.07.29 yeah i have the same problem.

Crash log?

**Comment by Fate970730** [comment]
https://crash.limetech.org/t73xw5gs4ygh
https://crash.limetech.org/ywcamvkbrbsa

**Comment by Fate970730** [comment]
> > 2023.07.29 igen, nekem is ugyanez a problémám.
> 
> Összeomlási napló?
https://crash.limetech.org/t73xw5gs4ygh
https://crash.limetech.org/ywcamvkbrbsa
https://crash.limetech.org/5ytbtg5gzwmu
