### ISSUE TITLE
[Bug] ff2r_menu_abilities Mana doesn't work

### ISSUE THREAD

**Issue by J0BL3SS** [Batfoxkid/Freak-Fortress-2-Rewrite#52]
## Description
When using mana for abilities, current mana showing random numbers, even higher than it's desired capacity. But only using cooldowns for abilities doesn't cause any problem

## Environment
 - OS: Windows 10 - 22H2 - 19045.2846
 - SourceMod Version 1.11 - Build 6934
 - Freak Fortress 1.1.110

## Other Information
Doesn't look like integer/float overflow

**Comment by Frixux** [comment]
Yeah, i have the same problem.
