### ISSUE TITLE
[Request] Make horizontal/forward force scale with special_mobility percent

### ISSUE THREAD

**Issue by DanishSoup** [Batfoxkid/Freak-Fortress-2-Rewrite#62]
## Description
When using super jump (special_mobility) with little charge will give you the about or the same forward force as charging super jump to full.
https://youtu.be/QKfi4u93h8Y
https://youtu.be/XcG9G3wK6HQ

## Applications
Super jumping with low percentages can allow the boss to do a "dash" without charging high (this is much more noticeable when the "forward" arg is set much higher than default (ex."2.0 + (n * 0.000275)"). Making it so that super jump scales with percent won't allow bosses to perform a "dash" with low percentages. Optionally it could be toggle-able within "special_mobility"

## Code Snippet
If applicable, a code snippet of the feature and the source if it came from someone else.

## Other Information
First demonstration shows both tapping and holding super jump but without any vertical differences and then showing both again with a more open area.
Second is the same but with a higher "forward" arg number.

**Comment by Batfoxkid** [comment]
This is already possible, the value `n` in the formula is the charge percent (0.0 to 100.0). If you wish to achieve a greater difference of forward movement, adjust the second number (`0.000275`) to a greater amount.
