### ISSUE TITLE
[Bug] Flying Guillotine Damage

### ISSUE THREAD

**Issue by DanishSoup** [Batfoxkid/Freak-Fortress-2-Rewrite#64]
## Description
When using "ff2r_default_abilities" "rage_new_weapon" to get a flying guillotine, attribute "2" won't affect its damage.

## Reproduce
1. Use "rage_new_weapon" to get a flying guillotine
2. Use attribute 2 to increase its damage (Ex. 2 ; 2.5)
3. Use boss with ability
4. See error (Damage will still be 50)

## Media
https://youtu.be/rumvVzC8EOQ

## Environment
 - OS: Linux Mint 21.2
 - SourceMod Version/Build: 1.11.0.6934
 - Freak Fortress Version/Build: 1.1.118

## Other Information
When looking at the server's console, each hit will display "AddMultiDamage:  g_MultiDamage.GetDamageForce() == vec3_origin"

**Comment by Batfoxkid** [comment]
This is an issue with the game itself, use attribute 138 to simulate a fix.
