### ISSUE TITLE
[Bug] Clipless ammo weapons won't switch after running out of ammo

### ISSUE THREAD

**Issue by DanishSoup** [Batfoxkid/Freak-Fortress-2-Rewrite#65]
## Description
When using "rage_new_weapon" with a clipless weapon, after running out of ammo the weapon will still be held out and can be switched back to.

## Reproduce
1. Use "rage_new_weapon" on a boss with a clipless weapon (Ex. flare gun, mad milk, minigun, etc)
2. Waste all ammo on the gun

## Media
Clipless weapon behavior: https://youtu.be/HaWsdo-Sabs
Weapon with clip behavior: https://youtu.be/fiDsyFjcWIk

## Environment
 - OS: Linux Mint 21.2
 - SourceMod Version/Build: 1.11.0.6934
 - Freak Fortress Version/Build: 1.1.118

**Comment by Batfoxkid** [comment]
Do you have clip amount set? That is known to cause issues.

**Comment by DanishSoup** [comment]
Config I got sent to test puts "35" on clip and "n" on ammo. It gives out 35 anyways so I'm not sure if thats the issue

**Comment by Batfoxkid** [comment]
> Config I got sent to test puts "35" on clip and "n" on ammo. It gives out 35 anyways so I'm not sure if thats the issue

Avoid both when working with clipless weapons.
