### ISSUE TITLE
[Bug] screen bug

### ISSUE THREAD

**Issue by Fate970730** [Batfoxkid/Freak-Fortress-2-Rewrite#76]
## Description
With certain FF2 Bosses, the feature is that the screen goes dark or something like that and as soon as you die, it stays there until you connect again.

## Reproduce
no error log

## Media
https://youtu.be/TwkQOWk9hcw

## Environment
 - OS: Linux
 - SourceMod 1.11.0.6936
 - Freak Fortress 1.1.124

## Other Information
no

**Comment by Batfoxkid** [comment]
This is not related to base FF2.

**Comment by Fate970730** [comment]
> This is not related to base FF2.
yes, I know custom boss, but why is there this error and how can I fix it?
