### ISSUE TITLE
[Bug] Crit-a-cola does not give crits when using attribute 179

### ISSUE THREAD

**Issue by DanishSoup** [Batfoxkid/Freak-Fortress-2-Rewrite#97]
## Description
Back in unofficial ff2, crit-a-cola would give crits when using attribute 179 to make mini-crits into crits for your other weapons like your scattergun. However in rewrite this is not the case and theres no way to make this happen even when using "mod crit type glow" "2"

## Reproduce
1. Edit crit-a-cola to have attribue 179 ; 1 or "mod crit type glow" "2"
2. Use crit-a-cola
3. Crit-a-cola only gives minicrits

## Media
If applicable, add screenshots, videos, logs, to help explain your problem.
https://youtu.be/P7g998PU3aE

## Environment
 - OS: Linux Mint 21.2
 - SourceMod Version/Build: 1.12.0.7043
 - Freak Fortress Version/Build: 1.1.137

**Comment by Batfoxkid** [comment]
Would be better off being an external custom attribute.
